
one = float(input ("Please Enter Your First Number\n"))
two = float(input ("Please Enter Your Second Number\n", ))
resultone = (one * two)
print ("The answer to your query is",resultone)
print("")
three = float(input ("Please Enter Your First Number\n", ))
four = float(input ("Please Enter Your Second Number\n", ))
result2 = (three / four)
print ("The answer to your query is",result2)
print("")
five = float(input ("Please Enter Your First Number\n", ))
six = float(input ("Please Enter Your Second Number\n", ))
result3 = (five // six)
print ("The answer to your query is",result3)
print("")
seven = float(input ("Please Enter Your First Number\n", ))
eight = float(input ("Please Enter Your Second Number\n", ))
result4 = (seven % eight)
print ("The answer to your query is",result4)
print("")
nine = float(input ("Please Enter Your First Number\n", ))
ten = float(input ("Please Enter Your Second Number\n", ))
result5 = int(nine + ten)
print ("The answer to your query is",result5)
print("")
eleven = float(input ("Please Enter Your First Number\n", ))
twelve = float(input ("Please Enter Your Second Number\n", ))
result6 = int(eleven - twelve)
print ("The answer to your query is",result6)
print("")
print("Kristofer Farris")




